# Generated by Django 3.1.6 on 2021-02-09 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="ShopData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Shop name"
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="Valid domain name"
                    ),
                ),
            ],
            options={"verbose_name": "Shop data", "verbose_name_plural": "Shops data"},
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Product name"
                    ),
                ),
                (
                    "ean",
                    models.CharField(
                        blank=True, max_length=17, null=True, verbose_name="ean"
                    ),
                ),
                (
                    "product_url",
                    models.URLField(unique=True, verbose_name="Url to product"),
                ),
                (
                    "last_parsing_data",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Last parsing price product date",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        max_length=150,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="products.shopdata",
                        verbose_name="Shop",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="favourite_products",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigned users",
                    ),
                ),
            ],
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
    ]
