# Generated by Django 3.1.6 on 2021-02-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("products", "0002_auto_20210209_0957")]

    operations = [
        migrations.AddField(
            model_name="product",
            name="last_parsed_price",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Last parsed price"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="url_to_scrape_product",
            field=models.CharField(
                max_length=500, unique=True, verbose_name="Url to scrape product"
            ),
        ),
    ]
