# Generated by Django 3.1.6 on 2021-02-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("products", "0003_auto_20210210_0948")]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_name",
            field=models.CharField(max_length=255, verbose_name="Product name"),
        )
    ]
